### ISSUE TITLE
Fix the enemies attack hitbox

### ISSUE THREAD

**Issue by 64kramsystem** [fishfight/punchy#156] opened 2022-07-26 20:45 UTC
### Description

The hitbox of the enemies attack is not correct; at least 50% of the times, the enemy attacks don't land; the hitbox seems to be too small.

**Comment by odecay** [comment] 2022-07-26 21:10
Depends what you mean by correct but its working as intended right now, the hitbox does not line up with the enemies hands as it is a box spawned ontop of the center. This will be left till attack hitbox size and offset are defined through fighter resource files.

**Comment by 64kramsystem** [comment] 2022-07-26 22:39
> Depends what you mean by correct but its working as intended right now, the hitbox does not line up with the enemies hands as it is a box spawned ontop of the center. This will be left till attack hitbox size and offset are defined through fighter resource files.

It's a bit strange. It seems that there are very slight difference, that cause hits to miss, when it seems that they should have landed.

I've made a video:

https://user-images.githubusercontent.com/1595356/181124237-462b74eb-8839-47fd-af49-027ea4581adf.mp4

There are a few instances of misses, one is for example at 0'37". Maybe it's something difference, for example, the Z coordinate :think

**Comment by 64kramsystem** [comment] 2022-07-26 22:43
I'll check with the hitboxes enabled :thinking:

**Comment by odecay** [comment] 2022-07-26 22:43
Okay thanks for the video, this is indeed what i pointed out above, both enemies currently use the same attack hitbox and frame properties. The hitbox does not line up with the attacks but I left it that way intentionally. I can quickly make the hitbox bigger before release to close this out but ultimately this will be addressed in https://github.com/fishfight/punchy/issues/157.

**Comment by 64kramsystem** [comment] 2022-07-26 22:44
> Okay thanks for the video, this is indeed what I pointed out above, both enemies currently use the same attack hitbox and frame properties. The hitbox does not line up with the attacks but I left it that way intentionally. I can quickly make the hitbox bigger before release to close this out but ultimately this will be addressed in #157.

I see. Thanks! That actually makes... the player easier to kill, which is something a bit hard right now :joy:

**Closed** 2022-07-26 23:41 UTC
Labels: kind:bug, scope:undetermined
